services:

  kafka:
    container_name: kafka
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    networks:
      - email-ms
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
      #    volumes:
      #      - ./data/kafka/data:/var/lib/kafka/data

  redpanda-console:
    container_name: redpanda
    image: docker.redpanda.com/vectorized/console:latest
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    ports:
      - "8081:8080"
    networks:
      - email-ms
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka:29092"]
    depends_on:
      - "kafka"

  user-service-db:
    image: postgres:latest
    container_name: user-service-db
    environment:
      POSTGRES_DB: user-service-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PG_DATA: /data/postgres
    networks:
      - email-ms

    ports:
      - "5432:5432"

  email-service-db:
    image: postgres:latest
    container_name: email-service-db
    environment:
      POSTGRES_DB: email-service-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PG_DATA: /data/postgres
    networks:
      - email-ms

    ports:
      - "5433:5432"

  user-service:
    build: ./user-service
    container_name: user-service
    networks:
      - email-ms
    depends_on:
      - kafka
      - user-service-db
    
    environment:
      KAFKA_BROKER: kafka:29092
      DB_HOST: user-service-db
      DB_PORT: 5432
      DB_NAME: user-service-db
      DB_USER: postgres
      DB_PASSWORD: postgres
    
    ports:
      - "8080:8080"
      
  email-service:
    build: ./email-service
    container_name: email-service
    networks:
      - email-ms
    depends_on:
      - kafka
      - email-service-db

    environment:
      KAFKA_BROKER: kafka:29092
      DB_HOST: email-service-db
      DB_PORT: 5432
      DB_NAME: email-service-db
      DB_USER: postgres
      DB_PASSWORD: postgres

      EMAIL: # E-mail do remetente
      PASSWORD_APP: # Senha ou token do e-mail (app password)
      MAIL_HOST: smtp.gmail.com # Pode mudar para o servidor SMTP usado, como SES
      MAIL_PORT: 587
      MAIL_PROTOCOL: smtp
      MAIL_SMTP_AUTH: "true"
      MAIL_SMTP_STARTTLS_ENABLE: "true"

    ports:
      - "8082:8082"

networks:
  email-ms:
    driver: bridge